# Generated by Django 6.0 on 2026-01-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='base_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=10, null=True),
        ),
    ]
