# Generated by Django 5.2.14 on 2026-05-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
